language: node_js
node_js:
- '16'
script:
- npm test
- npm run coveralls
- npm run build
deploy:
  provider: npm
  email: honzik.vaclav@gmail.com
  api_key:
    secure: X4D7AwNX7z6XW7LDLV8tgb2Skz2ArPKltNlLiYew/cbeWj0PN8hD+01nNjfe87GHGXrAbJoIJEsFi/MdnBOH1YzbaIiSHoMGCrT1J9PIpOSBaOMDG6tGKJMaXS6NhkqPVDQE0hz2KdTpPUdII+GhHMamjpTZ3KtdKsEL12mbwBgqEWnmpwLqlwroUwIZKUZcPZREurON7XDY9nqtHpkRkCybUK5jglW67ucW1Xg4ZEqQzMjs+GdOpCJFLwtFSTb42H+j0cN+OFWHFdGvAAHfQ9Ol7PejLaBRtLyGakS8qljZCvbm0lpgr9pqV32+WE6Y0FyLcHyjO4AssMBZ3DQXwhbLfYjiWbFW0/EMYFMggmZT+RJb9gIBVTTl0zgTQCbJO0DrqvRxjeXbGI9Vw5kspDQD+I9puWNHUr/dANmHNdZEW5/nirPoHJJGMN+r1EdkUBwIovxYbkdLo3Vb1eYxlZilZf7Yd8gL65aSRdPEcpoPzOQ7NkElpgCkfGKKbPsCHqwde9zJaNgvUsvKedp1yofA9TkCWV86vFkkdKnd4JrHOLJVDljK/ax73g1NApT5U/rNeDX8jl5amxumQb8GNR+xBwCY/Lh9YYaim/KzrjCUTA2d0eq4SOZdFstbSh7WeGcx7grg6R60GR76j18d1TuP7O8BJoIrVIszuSd8f/A=
  on:
    tags: true
    repo: VHonzik/web-gash
    branch: main
  skip_cleanup: 'true'
