language: node_js
node_js:
- '16'
script:
- npm test
- npm run coveralls
- npm run build
deploy:
  provider: npm
  email: honzik.vaclav@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: VHonzik/web-gash
    branch: main
  skip_cleanup: 'true'
