language: node_js
node_js:
- '16'
script:
- npm test
- npm run coveralls
- npm run build
deploy:
  provider: npm
  email: honzik.vaclav@gmail.com
  api_key:
    secure: NW9glzhde7TqRxxQAaCDNHK+SAqzO9fMUBTMYWYsflFnKyxmmfmI3XOda1MHuJ58+7KqnxK0okvU6xtLwbfSt24NL+pG4Tz4zy/cbPYnVDsnJu6hNSLsm2IC1eQpIDYgRYOvfurtVrhiIkhgErebMggb2WNaERD4X1NslyRfUN0dv5AkP6An8mO1H5A/EYZQjltYVwFGIVi6SWQbIkxExeG3osLl4AFe6xA0ERE/b5aUCi2qv9TIWYEXN2S5zh9GsPfmNrkR2+jTsGO4XQm1uhHCyWmfNesTvofkt+0+HvRaB/5HYAFTgp+IxxmPREe1vXIVQJV/Cb4Zf3uIyG1jgFR037UfpBX+tlCV5biIZ/A2G6BUao5mEoZuk66Bu9o4QzWAhZ120+IYYULZRY61/KbLempY9lKc44sqDP5vNf7r1pbST8b8Y1ruTeNe1hpOtX59mu7SGgWu5DyoDfYksBHyV9C89Q4KzEz/hGJR562KRhZ+zXjaD8+pZGrnyxdnfuvm6hRNAGcVKA/Mp/m0x0vTn8I8Fw7VA/S5mX6t/mlrP0YOgoeESwLf5bs9tMnT4cPmOtNHNvNZqLw9aAbxK6ZKu+pxKGNqXoE8WRWueLGQz1MjcaaQI0S4Pg0GXr6yJbT7ZDi+6xUDG5HKp+cizw8HmIaiXQnsmGjTwNfJahY=
  on:
    tags: true
    repo: VHonzik/web-gash
    branch: main
  skip_cleanup: 'true'
